sudo: required

services: docker

before_install:
  - docker-compose up --build -d

script: 
  - docker-compose run back bundle exec rspec
  - docker-compose run front ng test --watch false
  - docker-compose run front ng e2e

notifications:
  email: false
