version: '2'
services:
  db:
    image: postgres

  back:
    build: casalimpia-back
    image: yovasx2/casalimpia-back
    volumes:
      - ./casalimpia-back:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
  
  front:
    build: casalimpia-front
    image: yovasx2/casalimpia-front
    volumes:
      - ./casalimpia-front:/app
    ports:
      - "4200:4200"